language: node_js
node_js:
    - '6'
    - '8'
    - '9'
    - '10'
sudo: false
env:
    - FORCE_COLOR=true
before_install:
    - sh scripts/ci.sh
script:
    - npm run-script ci
    - npm link
    - gh
after_success:
    - sh scripts/ci-reports.sh
