language: node_js
sudo: false
node_js:
    - '6'
    - '8'
    - 'lts/*'
    - 'node'
env:
    - FORCE_COLOR=true

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
    only:
        - master
        - type != push

script:
    - npm run-script test:ci
    - npm link

jobs:
    include:
        - stage: release
          node_js: lts/*
          script: npx semantic-release

stages:
    - test
    - name: release
      if: repo = node-gh/gh AND branch = master AND type IN (push)
